spring.application.name=gateway

server.port=8085

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch.registry=true

#gateway
spring.cloud.gateway.routes[0].id=companyms
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/companies/**

spring.cloud.gateway.routes[1].id=jobms
spring.cloud.gateway.routes[1].uri=http://localhost:8082
#.uri=lb://jobms-dev lb stands for load balance which is used: distribute request evenly
spring.cloud.gateway.routes[1].predicates[0]=Path=/jobs/**

spring.cloud.gateway.routes[2].id=reviewms
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/reviews/**

spring.cloud.gateway.routes[3].id=authService
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

#added eureka server
spring.cloud.gateway.routes[4].id=eureka-server
# pointed it to url where actual server is running
spring.cloud.gateway.routes[4].uri=http://localhost:8761
# specified the path
spring.cloud.gateway.routes[4].predicates[0]=Path=/eureka/main
# simply to run eureka on 8085 port
spring.cloud.gateway.routes[4].filters[0]=SetPath=/

# Everything is running on one port 8085
#for html and css part of 8085 eureka
spring.cloud.gateway.routes[5].id=eureka-server-static
spring.cloud.gateway.routes[5].uri=http://localhost:8761
spring.cloud.gateway.routes[5].predicates[0]=Path=/eureka/**


logging.level.root=info
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
